---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# georustr

<!-- badges: start -->
<!-- badges: end -->

This is a minimal R package to test calling Rust code from R.

Rebuild it with:

```{r}
rextendr::document()
```


Load it with:

```{r}
devtools::load_all()
```


When it is complete, the following should work:

```{r}
n = 1e5
points_df = data.frame(x = rnorm(n = n), y = rnorm(n))
system.time({
  points_sf = sf::st_as_sf(points_df, coords = c("x", "y"), crs = 4326)
})
```

We can do the full csv to geojson process for a fair test as follows:

```{r, eval=FALSE}
# run once
readr::write_csv(points_df, "points.csv")
```


```{r}
if(file.exists("points.geojson")) file.remove("points.geojson")
system.time({
  csv_to_json_base_r(file_csv = "points.csv")
})
file.exists("points.geojson")
```

```{r}
if(file.exists("points_rust.geojson")) {
  file.remove("points_rust.geojson")
}
system.time({
  csv_to_geojson_rust()
})
file.exists("points_rust.geojson")
```

You can also run the code from the system command line:

```bash
cd src/rust
cargo test --release
```

Verify the time taken to run as follows:

```bash
time cargo test --release
```

Check the output:

```{r}
sf::read_sf("points.geojson")
sf::read_sf("points_rust.geojson")
```




```{r, eval=FALSE}

system.time({
  points_georust = georustr::make_points(points_df)
})

```

