# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_georustr_wrappers", use_symbols = TRUE, package_name = "georustr")

#' @docType package
#' @usage NULL
#' @useDynLib georustr, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
hello_world <- function() .Call(wrap__hello_world)

#' Convert `points.csv` to points_rust.geojson.
#' @export
csv_to_geojson <- function() invisible(.Call(wrap__csv_to_geojson))

